namespace DirectDimensional.Bindings.Direct3D11 {
    public enum D3D_SHADER_INPUT_TYPE {
        CBuffer = 0,
        TBuffer,
        Texture,
        Sampler,
        UAV_RWTyped,
        Structured,
        UAV_RWStructured,
        ByteAddress,
        UAV_RWByteAddress,
        UAV_AppendStructured,
        UAV_ConsumeStructured,
        UAV_RWStructured_With_Counter,
        RTAccelerationStructure,
        UAV_FeedbackTexture,
        D3D10_CBuffer,
        D3D10_TBuffer,
        D3D10_Texture,
        D3D10_Sampler,
        D3D11_UAV_RWTyped,
        D3D11_Structured,
        D3D11_UAV_RWStructured,
        D3D11_ByteAddress,
        D3D11_UAV_RWByteAddress,
        D3D11_UAV_AppendStructured,
        D3D11_UAV_ConsumeStructured,
        D3D11_UAV_RWStructured_With_Counter,
    }
}
