namespace DirectDimensional.Bindings.D3DCompiler {
    public enum D3D_NAME {
        Undefined = 0,
        Position = 1,
        ClipDistance = 2,
        CullDistance = 3,
        RenderTargetArrayIndex = 4,
        ViewportArrayIndex = 5,
        VertexID = 6,
        PrimitiveID = 7,
        InstanceID = 8,
        IsFrontFace = 9,
        SampleIndex = 10,
        FinalQuadEdgeTessfactor = 11,
        FinalQuadInsideTessfactor = 12,
        FinalTriEdgeTessfactor = 13,
        FinalTriInsideTessfactor = 14,
        FinalLineDetailTessfactor = 15,
        FinalLineDensityTessfactor = 16,
        Barycentrics = 23,
        ShadingRate,
        CullPrimitive,
        Target = 64,
        Depth = 65,
        Coverage = 66,
        DepthGreaterEqual = 67,
        DepthLessEqual = 68,
        StencilRef = 69,
        InnerCoverage = 70,
        D3D10_Undefined,
        D3D10_Position,
        D3D10_ClipDistance,
        D3D10_CullDistance,
        D3D10_RenderTargetArrayIndex,
        D3D10_ViewportArrayIndex,
        D3D10_VertexID,
        D3D10_PrimitiveID,
        D3D10_InstanceID,
        D3D10_IsFrontFace,
        D3D10_SampleIndex,
        D3D10_Target,
        D3D10_Depth,
        D3D10_Coverage,
        D3D11_FinalQuadEdgeTessfactor,
        D3D11_FinalQuadInsideTessfactor,
        D3D11_FinalTriEdgeTessfactor,
        D3D11_FinalTriInsideTessfactor,
        D3D11_FinalLineDetailTessfactor,
        D3D11_FinalLineDensityTessfactor,
        D3D11_DepthGreaterEqual,
        D3D11_DepthLessEqual,
        D3D11_StencilRef,
        D3D11_InnerCoverage,
        D3D12_Barycentrics,
        D3D12_ShadingRate,
        D3D12_CullPrimitive
    }
}
